exports.members = [
    // {name: 'Ayrrows'},
    // {name: 'Barf'},
    {name: 'Bearstick'},
    {name: 'Blårn'},
    {name: 'Brogainz'},
    {name: 'Cedís'},
    {name: 'Chimlee'},
    {name: 'Deathvader'},
    {name: 'Doôm'},
    {name: 'Eeyr'},
    // {name: 'Egghunt'},
    // {name: 'Errlin'},
    {name: 'Fishbomb'},
    // {name: 'Garnok'},
    {name: 'Ghalleon'},
    {name: 'Gynis'},
    {name: 'Iridéssa'},
    {name: 'Kornith'},
    {name: 'Necrasa'},
    {name: 'Picarohuevos'},
    {name: 'Pooveysnacks'},
    // {name: 'Rendymoss'},
    {name: 'Rÿzer'},
    {name: 'Samulath'},
    {name: 'Shaawa'},
    {name: 'Shamfoyle'},
    // {name: 'Sploitt'},
    {name: 'Stangmeister'},
    {name: 'Titanflame'},
    {name: 'Tórz'},
    {name: 'Vaninn'},
    // {name: 'Vierria'},
    {name: 'Wínzíg'},
    // {name: 'Zrankah'}
];
